import { Suspense } from "react";
import { dehydrate, HydrationBoundary } from "@tanstack/react-query";

import type { Metadata } from "next";
import { getQueryClient, trpc } from "@/trpc/server";
import "../globals.css";
import Navbar from "./navbar";
import Footer from "./footer";
import SearchFilters, { SearchFiltersSkeleton } from "./search-filters";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const queryClient = getQueryClient();
  void queryClient.prefetchQuery(trpc.categories.getMany.queryOptions());

  return (
    <div className="flex flex-col min-h-screen">
      <Navbar />
      <HydrationBoundary state={dehydrate(queryClient)}>
        <Suspense fallback={<SearchFiltersSkeleton />}>
          <SearchFilters />
        </Suspense>
      </HydrationBoundary>
      <main className="flex-1 bg-[#f4f4f4]">{children}</main>
      <Footer />
    </div>
  );
}
