import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "../globals.css";
import Navbar from "./navbar";
import Footer from "./footer";

const dmSans = DM_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmSans.className} antialiased`}>
        <div className="flex flex-col min-h-screen">
          <Navbar />
          <main className="flex-1 bg-[#f4f4f4]">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
